### ISSUE TITLE
Paytm plugin call issue

### ISSUE THREAD

**Issue by jinku281** [narendra-ct/Cordova-Paytm-Plugin#1]
Hello,
I have installed this plugin for ionic2 app.plugin installed successfully but when i call method PaytmPlugin.payWithPaytm() i have an error can not find name PaytmPlugin.please help me about this issue

**Comment by narendra-ct** [comment]
@ jinku281 : Are you passing require parameters with **payWithPaytm()** method?

**Comment by redoc123** [comment]
add the following line to your src/typings.d.ts file:

declare var PaytmPlugin:any;

**Comment by Anju-Jacob** [comment]
you can declare PaytmPlugin in class where ever you are using.

**declare var PaytmPlugin:any;**
